# Generated by Django 2.1.4 on 2018-12-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('titular', models.CharField(max_length=50)),
                ('resumen', models.TextField()),
                ('tipo', models.CharField(choices=[('Deportes', 'Deportes'), ('Cultura', 'Cultura')], max_length=100)),
                ('autores', models.ManyToManyField(to='principal.Autor')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuarios',
            field=models.ManyToManyField(to='principal.Usuario'),
        ),
    ]
